[package]
name = "roblox/roact-rodux"
author = "Roblox"
license = "Apache-2.0"
content_root = "src"
version = "0.3.0"

[dependencies]
Roact = "github.com/roblox/roact@1.3"
Rodux = "github.com/roblox/rodux@1.0"
